_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    '': null
    fr: fr
    zh-hans: zh-hans
    es: es
    ar: ar
    ru: ru
  domains:
    en: ''
    fr: ''
    zh-hans: ''
    es: ''
    ar: ''
    ru: ''
selected_langcode: site_default
